### GET /
GET http://localhost:8080 HTTP/1.1

### POST /auth/register
POST http://localhost:8080/auth/register HTTP/1.1
Content-Type: application/json

{
  	"email": "test@gmail.com",
  	"password": "John123!",
  	"confirm_password": "John123!"
}

### POST /auth/login
POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmail.com",
  	"password": "John123!"
}

### PATCH /users/:id
PATCH http://localhost:8080/users/0f96404a-7968-4570-893e-b7c128514b9b HTTP/1.1
Content-Type: application/json

{
  	"role_id": "80ce4f22-cfdd-41da-9b0d-3b84a937edbf"
}

### GET /auth
GET  http://localhost:8080/auth HTTP/1.1

### POST /auth/signout
POST http://localhost:8080/auth/signout HTTP/1.1



### GET /users
GET http://localhost:8080/users HTTP/1.1

### GET /permissions
GET http://localhost:8080/permissions HTTP/1.1

### POST /permissions
POST http://localhost:8080/permissions HTTP/1.1
Content-Type: application/json 

{
	"name": "edit_permissions"
}

### GET /roles
GET http://localhost:8080/roles HTTP/1.1

### DELETE /roles/:id
DELETE http://localhost:8080/roles/c0123208-6192-463f-b29a-bb673b518191 HTTP/1.1

### POST /roles
POST http://localhost:8080/roles HTTP/1.1
Content-Type: application/json

{
	"name": "Viewer",
	"permissions": ["012aeb98-d21c-4c42-8804-7d314d0b2643"]
}

### PATCH /roles/:id
PATCH http://localhost:8080/roles/4a6206ca-5208-4775-a019-8bb8a28f0411 HTTP/1.1
Content-Type: application/json

{
	"name":"Admin",
	"permissions":["47b32317-152f-4c63-8c8d-d9a1880cbf32","4d6fcf64-8636-45e3-b36b-2a66a4891b9e"]
}